# The URL the site will be built for
base_url = "https://nicoladen.dev"
title = "Nicoladen"
author = "nicoladen"
theme = "linkita"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false
insert_anchor_links = "none"

[extra]
# Put all your custom variables here

[extra.style]
header_blur = true

bg_color = "#f4f4f5"
bg_dark_color = "#18181b"

header_color = "#f4f4f5"
header_dark_color = "#18181b"

[extra.profiles.nicoladen]
name = "Nicoladen"
bio = ""

avatar_url = ""
avatar_alt = ""

social = [
	{ name = "github", url = "https://github.com/nicoladen05"},
	{ name = "youtube", url = "https://www.youtube.com/@nico9988"},
	{ name = "spotify", url = "https://open.spotify.com/user/31ojqlwww76kdyqxdhbm7xbx6fgi?si=7a55dd6ab7284f1e"},
	{ name = "email", url = "mailto:hello@nicoladen.dev"},
]
